//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tamkeen.IndividualsServices.Services.ServiceReference
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ImmediateApproveQuotaInfo", Namespace = "http://tempuri.org/")]
    public partial class ImmediateApproveQuotaInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int AutoApprovalQuotaField;

        private int AllowedNitaqLimitField;

        private int UnusedVISACreditField;

        private int MinimumForeignersField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int AutoApprovalQuota
        {
            get
            {
                return this.AutoApprovalQuotaField;
            }
            set
            {
                this.AutoApprovalQuotaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public int AllowedNitaqLimit
        {
            get
            {
                return this.AllowedNitaqLimitField;
            }
            set
            {
                this.AllowedNitaqLimitField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public int UnusedVISACredit
        {
            get
            {
                return this.UnusedVISACreditField;
            }
            set
            {
                this.UnusedVISACreditField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public int MinimumForeigners
        {
            get
            {
                return this.MinimumForeignersField;
            }
            set
            {
                this.MinimumForeignersField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "NitaqatServiceReference.EstablishmentKPIWebServiceSoap")]
    public interface EstablishmentKPIWebServiceSoap
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEstablishmentQuota", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentQuotaResponse GetEstablishmentQuota(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentQuotaRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEstablishmentQuota", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentQuotaResponse> GetEstablishmentQuotaAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentQuotaRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEstablishmentColor", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentColorResponse GetEstablishmentColor(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentColorRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEstablishmentColor", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentColorResponse> GetEstablishmentColorAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentColorRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEntitySaudiLaborersCountByEstablishmentNumber", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.GetEntitySaudiLaborersCountByEstablishmentNumberResponse GetEntitySaudiLaborersCountByEstablishmentNumber(Tamkeen.IndividualsServices.Services.ServiceReference.GetEntitySaudiLaborersCountByEstablishmentNumberRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEntitySaudiLaborersCountByEstablishmentNumber", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEntitySaudiLaborersCountByEstablishmentNumberResponse> GetEntitySaudiLaborersCountByEstablishmentNumberAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEntitySaudiLaborersCountByEstablishmentNumberRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEstablishmentExcellentLimit", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentExcellentLimitResponse GetEstablishmentExcellentLimit(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentExcellentLimitRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEstablishmentExcellentLimit", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentExcellentLimitResponse> GetEstablishmentExcellentLimitAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentExcellentLimitRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEstablishmentHighGreenLimit", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentHighGreenLimitResponse GetEstablishmentHighGreenLimit(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentHighGreenLimitRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEstablishmentHighGreenLimit", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentHighGreenLimitResponse> GetEstablishmentHighGreenLimitAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentHighGreenLimitRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEWVAutoApprovalQuota", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.GetEWVAutoApprovalQuotaResponse GetEWVAutoApprovalQuota(Tamkeen.IndividualsServices.Services.ServiceReference.GetEWVAutoApprovalQuotaRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEWVAutoApprovalQuota", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEWVAutoApprovalQuotaResponse> GetEWVAutoApprovalQuotaAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEWVAutoApprovalQuotaRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEstablishmentMediumGreenLimit", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentMediumGreenLimitResponse GetEstablishmentMediumGreenLimit(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentMediumGreenLimitRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEstablishmentMediumGreenLimit", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentMediumGreenLimitResponse> GetEstablishmentMediumGreenLimitAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentMediumGreenLimitRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEstablishmentLowGreenLimit", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentLowGreenLimitResponse GetEstablishmentLowGreenLimit(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentLowGreenLimitRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEstablishmentLowGreenLimit", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentLowGreenLimitResponse> GetEstablishmentLowGreenLimitAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentLowGreenLimitRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEstablishmentYellowLimit", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentYellowLimitResponse GetEstablishmentYellowLimit(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentYellowLimitRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEstablishmentYellowLimit", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentYellowLimitResponse> GetEstablishmentYellowLimitAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentYellowLimitRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetCompansationVisasForEstablishment", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.GetCompansationVisasForEstablishmentResponse GetCompansationVisasForEstablishment(Tamkeen.IndividualsServices.Services.ServiceReference.GetCompansationVisasForEstablishmentRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetCompansationVisasForEstablishment", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetCompansationVisasForEstablishmentResponse> GetCompansationVisasForEstablishmentAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetCompansationVisasForEstablishmentRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetCompansationVisasForEntity", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.GetCompansationVisasForEntityResponse GetCompansationVisasForEntity(Tamkeen.IndividualsServices.Services.ServiceReference.GetCompansationVisasForEntityRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetCompansationVisasForEntity", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetCompansationVisasForEntityResponse> GetCompansationVisasForEntityAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetCompansationVisasForEntityRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEstablishmentPendingUnUsedVisas", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentPendingUnUsedVisasResponse GetEstablishmentPendingUnUsedVisas(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentPendingUnUsedVisasRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEstablishmentPendingUnUsedVisas", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentPendingUnUsedVisasResponse> GetEstablishmentPendingUnUsedVisasAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentPendingUnUsedVisasRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEntityPendingUnUsedVisas", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityPendingUnUsedVisasResponse GetEntityPendingUnUsedVisas(Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityPendingUnUsedVisasRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEntityPendingUnUsedVisas", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityPendingUnUsedVisasResponse> GetEntityPendingUnUsedVisasAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityPendingUnUsedVisasRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/CheckQuotaForVerySmallEntities", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForVerySmallEntitiesResponse CheckQuotaForVerySmallEntities(Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForVerySmallEntitiesRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/CheckQuotaForVerySmallEntities", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForVerySmallEntitiesResponse> CheckQuotaForVerySmallEntitiesAsync(Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForVerySmallEntitiesRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/CheckQuotaForVerySmallEntitiesForTargetColor", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForVerySmallEntitiesForTargetColor1 CheckQuotaForVerySmallEntities1(Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForVerySmallEntitiesForTargetColor request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/CheckQuotaForVerySmallEntitiesForTargetColor", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForVerySmallEntitiesForTargetColor1> CheckQuotaForVerySmallEntities1Async(Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForVerySmallEntitiesForTargetColor request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/CheckQuotaForWhiteEstablishment", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForWhiteEstablishmentResponse CheckQuotaForWhiteEstablishment(Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForWhiteEstablishmentRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/CheckQuotaForWhiteEstablishment", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForWhiteEstablishmentResponse> CheckQuotaForWhiteEstablishmentAsync(Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForWhiteEstablishmentRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/CheckQuotaForWhiteEstablishmentForTargetColor", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForWhiteEstablishmentForTargetColor1 CheckQuotaForWhiteEstablishment1(Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForWhiteEstablishmentForTargetColor request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/CheckQuotaForWhiteEstablishmentForTargetColor", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForWhiteEstablishmentForTargetColor1> CheckQuotaForWhiteEstablishment1Async(Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForWhiteEstablishmentForTargetColor request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEntityCurrentTotalNumberofLaborers", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityCurrentTotalNumberofLaborersResponse GetEntityCurrentTotalNumberofLaborers(Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityCurrentTotalNumberofLaborersRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEntityCurrentTotalNumberofLaborers", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityCurrentTotalNumberofLaborersResponse> GetEntityCurrentTotalNumberofLaborersAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityCurrentTotalNumberofLaborersRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEntityUnUsedVisas", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityUnUsedVisasResponse GetEntityUnUsedVisas(Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityUnUsedVisasRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetEntityUnUsedVisas", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityUnUsedVisasResponse> GetEntityUnUsedVisasAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityUnUsedVisasRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ValidateEstablishmentEntityHistory", ReplyAction = "*")]
        Tamkeen.IndividualsServices.Services.ServiceReference.ValidateEstablishmentEntityHistoryResponse ValidateEstablishmentEntityHistory(Tamkeen.IndividualsServices.Services.ServiceReference.ValidateEstablishmentEntityHistoryRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ValidateEstablishmentEntityHistory", ReplyAction = "*")]
        System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.ValidateEstablishmentEntityHistoryResponse> ValidateEstablishmentEntityHistoryAsync(Tamkeen.IndividualsServices.Services.ServiceReference.ValidateEstablishmentEntityHistoryRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEstablishmentQuota", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEstablishmentQuotaRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int laborOfficeId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public long sequenceNumber;

        public GetEstablishmentQuotaRequest()
        {
        }

        public GetEstablishmentQuotaRequest(int laborOfficeId, long sequenceNumber)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEstablishmentQuotaResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEstablishmentQuotaResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int GetEstablishmentQuotaResult;

        public GetEstablishmentQuotaResponse()
        {
        }

        public GetEstablishmentQuotaResponse(int GetEstablishmentQuotaResult)
        {
            this.GetEstablishmentQuotaResult = GetEstablishmentQuotaResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEstablishmentColor", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEstablishmentColorRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int laborOfficeId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public long sequenceNumber;

        public GetEstablishmentColorRequest()
        {
        }

        public GetEstablishmentColorRequest(int laborOfficeId, long sequenceNumber)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEstablishmentColorResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEstablishmentColorResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int GetEstablishmentColorResult;

        public GetEstablishmentColorResponse()
        {
        }

        public GetEstablishmentColorResponse(int GetEstablishmentColorResult)
        {
            this.GetEstablishmentColorResult = GetEstablishmentColorResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEntitySaudiLaborersCountByEstablishmentNumber", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEntitySaudiLaborersCountByEstablishmentNumberRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int laborOfficeId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public long sequenceNumber;

        public GetEntitySaudiLaborersCountByEstablishmentNumberRequest()
        {
        }

        public GetEntitySaudiLaborersCountByEstablishmentNumberRequest(int laborOfficeId, long sequenceNumber)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEntitySaudiLaborersCountByEstablishmentNumberResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEntitySaudiLaborersCountByEstablishmentNumberResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int GetEntitySaudiLaborersCountByEstablishmentNumberResult;

        public GetEntitySaudiLaborersCountByEstablishmentNumberResponse()
        {
        }

        public GetEntitySaudiLaborersCountByEstablishmentNumberResponse(int GetEntitySaudiLaborersCountByEstablishmentNumberResult)
        {
            this.GetEntitySaudiLaborersCountByEstablishmentNumberResult = GetEntitySaudiLaborersCountByEstablishmentNumberResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEstablishmentExcellentLimit", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEstablishmentExcellentLimitRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int laborOfficeId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public long sequenceNumber;

        public GetEstablishmentExcellentLimitRequest()
        {
        }

        public GetEstablishmentExcellentLimitRequest(int laborOfficeId, long sequenceNumber)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEstablishmentExcellentLimitResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEstablishmentExcellentLimitResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int GetEstablishmentExcellentLimitResult;

        public GetEstablishmentExcellentLimitResponse()
        {
        }

        public GetEstablishmentExcellentLimitResponse(int GetEstablishmentExcellentLimitResult)
        {
            this.GetEstablishmentExcellentLimitResult = GetEstablishmentExcellentLimitResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEstablishmentHighGreenLimit", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEstablishmentHighGreenLimitRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int laborOfficeId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public long sequenceNumber;

        public GetEstablishmentHighGreenLimitRequest()
        {
        }

        public GetEstablishmentHighGreenLimitRequest(int laborOfficeId, long sequenceNumber)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEstablishmentHighGreenLimitResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEstablishmentHighGreenLimitResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int GetEstablishmentHighGreenLimitResult;

        public GetEstablishmentHighGreenLimitResponse()
        {
        }

        public GetEstablishmentHighGreenLimitResponse(int GetEstablishmentHighGreenLimitResult)
        {
            this.GetEstablishmentHighGreenLimitResult = GetEstablishmentHighGreenLimitResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetEWVAutoApprovalQuotaRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetEWVAutoApprovalQuota", Namespace = "http://tempuri.org/", Order = 0)]
        public Tamkeen.IndividualsServices.Services.ServiceReference.GetEWVAutoApprovalQuotaRequestBody Body;

        public GetEWVAutoApprovalQuotaRequest()
        {
        }

        public GetEWVAutoApprovalQuotaRequest(Tamkeen.IndividualsServices.Services.ServiceReference.GetEWVAutoApprovalQuotaRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class GetEWVAutoApprovalQuotaRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public int laborOfficeId;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public long sequenceNumber;

        public GetEWVAutoApprovalQuotaRequestBody()
        {
        }

        public GetEWVAutoApprovalQuotaRequestBody(int laborOfficeId, long sequenceNumber)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetEWVAutoApprovalQuotaResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetEWVAutoApprovalQuotaResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public Tamkeen.IndividualsServices.Services.ServiceReference.GetEWVAutoApprovalQuotaResponseBody Body;

        public GetEWVAutoApprovalQuotaResponse()
        {
        }

        public GetEWVAutoApprovalQuotaResponse(Tamkeen.IndividualsServices.Services.ServiceReference.GetEWVAutoApprovalQuotaResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class GetEWVAutoApprovalQuotaResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Tamkeen.IndividualsServices.Services.ServiceReference.ImmediateApproveQuotaInfo GetEWVAutoApprovalQuotaResult;

        public GetEWVAutoApprovalQuotaResponseBody()
        {
        }

        public GetEWVAutoApprovalQuotaResponseBody(Tamkeen.IndividualsServices.Services.ServiceReference.ImmediateApproveQuotaInfo GetEWVAutoApprovalQuotaResult)
        {
            this.GetEWVAutoApprovalQuotaResult = GetEWVAutoApprovalQuotaResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEstablishmentMediumGreenLimit", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEstablishmentMediumGreenLimitRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int laborOfficeId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public long sequenceNumber;

        public GetEstablishmentMediumGreenLimitRequest()
        {
        }

        public GetEstablishmentMediumGreenLimitRequest(int laborOfficeId, long sequenceNumber)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEstablishmentMediumGreenLimitResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEstablishmentMediumGreenLimitResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int GetEstablishmentMediumGreenLimitResult;

        public GetEstablishmentMediumGreenLimitResponse()
        {
        }

        public GetEstablishmentMediumGreenLimitResponse(int GetEstablishmentMediumGreenLimitResult)
        {
            this.GetEstablishmentMediumGreenLimitResult = GetEstablishmentMediumGreenLimitResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEstablishmentLowGreenLimit", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEstablishmentLowGreenLimitRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int laborOfficeId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public long sequenceNumber;

        public GetEstablishmentLowGreenLimitRequest()
        {
        }

        public GetEstablishmentLowGreenLimitRequest(int laborOfficeId, long sequenceNumber)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEstablishmentLowGreenLimitResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEstablishmentLowGreenLimitResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int GetEstablishmentLowGreenLimitResult;

        public GetEstablishmentLowGreenLimitResponse()
        {
        }

        public GetEstablishmentLowGreenLimitResponse(int GetEstablishmentLowGreenLimitResult)
        {
            this.GetEstablishmentLowGreenLimitResult = GetEstablishmentLowGreenLimitResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEstablishmentYellowLimit", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEstablishmentYellowLimitRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int laborOfficeId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public long sequenceNumber;

        public GetEstablishmentYellowLimitRequest()
        {
        }

        public GetEstablishmentYellowLimitRequest(int laborOfficeId, long sequenceNumber)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEstablishmentYellowLimitResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEstablishmentYellowLimitResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int GetEstablishmentYellowLimitResult;

        public GetEstablishmentYellowLimitResponse()
        {
        }

        public GetEstablishmentYellowLimitResponse(int GetEstablishmentYellowLimitResult)
        {
            this.GetEstablishmentYellowLimitResult = GetEstablishmentYellowLimitResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetCompansationVisasForEstablishment", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetCompansationVisasForEstablishmentRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int laborOfficeId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public long sequenceNumber;

        public GetCompansationVisasForEstablishmentRequest()
        {
        }

        public GetCompansationVisasForEstablishmentRequest(int laborOfficeId, long sequenceNumber)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetCompansationVisasForEstablishmentResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetCompansationVisasForEstablishmentResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int GetCompansationVisasForEstablishmentResult;

        public GetCompansationVisasForEstablishmentResponse()
        {
        }

        public GetCompansationVisasForEstablishmentResponse(int GetCompansationVisasForEstablishmentResult)
        {
            this.GetCompansationVisasForEstablishmentResult = GetCompansationVisasForEstablishmentResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetCompansationVisasForEntity", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetCompansationVisasForEntityRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int laborOfficeId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public long sequenceNumber;

        public GetCompansationVisasForEntityRequest()
        {
        }

        public GetCompansationVisasForEntityRequest(int laborOfficeId, long sequenceNumber)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetCompansationVisasForEntityResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetCompansationVisasForEntityResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int GetCompansationVisasForEntityResult;

        public GetCompansationVisasForEntityResponse()
        {
        }

        public GetCompansationVisasForEntityResponse(int GetCompansationVisasForEntityResult)
        {
            this.GetCompansationVisasForEntityResult = GetCompansationVisasForEntityResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEstablishmentPendingUnUsedVisas", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEstablishmentPendingUnUsedVisasRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int laborOfficeId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public long sequenceNumber;

        public GetEstablishmentPendingUnUsedVisasRequest()
        {
        }

        public GetEstablishmentPendingUnUsedVisasRequest(int laborOfficeId, long sequenceNumber)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEstablishmentPendingUnUsedVisasResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEstablishmentPendingUnUsedVisasResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int GetEstablishmentPendingUnUsedVisasResult;

        public GetEstablishmentPendingUnUsedVisasResponse()
        {
        }

        public GetEstablishmentPendingUnUsedVisasResponse(int GetEstablishmentPendingUnUsedVisasResult)
        {
            this.GetEstablishmentPendingUnUsedVisasResult = GetEstablishmentPendingUnUsedVisasResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEntityPendingUnUsedVisas", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEntityPendingUnUsedVisasRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int laborOfficeId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public long sequenceNumber;

        public GetEntityPendingUnUsedVisasRequest()
        {
        }

        public GetEntityPendingUnUsedVisasRequest(int laborOfficeId, long sequenceNumber)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEntityPendingUnUsedVisasResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEntityPendingUnUsedVisasResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int GetEntityPendingUnUsedVisasResult;

        public GetEntityPendingUnUsedVisasResponse()
        {
        }

        public GetEntityPendingUnUsedVisasResponse(int GetEntityPendingUnUsedVisasResult)
        {
            this.GetEntityPendingUnUsedVisasResult = GetEntityPendingUnUsedVisasResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CheckQuotaForVerySmallEntities", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class CheckQuotaForVerySmallEntitiesRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int laborOfficeId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public long sequenceNumber;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
        public int requestedQuota;

        public CheckQuotaForVerySmallEntitiesRequest()
        {
        }

        public CheckQuotaForVerySmallEntitiesRequest(int laborOfficeId, long sequenceNumber, int requestedQuota)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
            this.requestedQuota = requestedQuota;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CheckQuotaForVerySmallEntitiesResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class CheckQuotaForVerySmallEntitiesResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public bool CheckQuotaForVerySmallEntitiesResult;

        public CheckQuotaForVerySmallEntitiesResponse()
        {
        }

        public CheckQuotaForVerySmallEntitiesResponse(bool CheckQuotaForVerySmallEntitiesResult)
        {
            this.CheckQuotaForVerySmallEntitiesResult = CheckQuotaForVerySmallEntitiesResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CheckQuotaForVerySmallEntitiesForTargetColor", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class CheckQuotaForVerySmallEntitiesForTargetColor
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int laborOfficeId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public long sequenceNumber;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
        public int requestedQuota;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
        public int targetColorId;

        public CheckQuotaForVerySmallEntitiesForTargetColor()
        {
        }

        public CheckQuotaForVerySmallEntitiesForTargetColor(int laborOfficeId, long sequenceNumber, int requestedQuota, int targetColorId)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
            this.requestedQuota = requestedQuota;
            this.targetColorId = targetColorId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CheckQuotaForVerySmallEntitiesForTargetColorResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class CheckQuotaForVerySmallEntitiesForTargetColor1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public bool CheckQuotaForVerySmallEntitiesForTargetColorResult;

        public CheckQuotaForVerySmallEntitiesForTargetColor1()
        {
        }

        public CheckQuotaForVerySmallEntitiesForTargetColor1(bool CheckQuotaForVerySmallEntitiesForTargetColorResult)
        {
            this.CheckQuotaForVerySmallEntitiesForTargetColorResult = CheckQuotaForVerySmallEntitiesForTargetColorResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CheckQuotaForWhiteEstablishment", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class CheckQuotaForWhiteEstablishmentRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int laborOfficeId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public long sequenceNumber;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
        public int requestedQuota;

        public CheckQuotaForWhiteEstablishmentRequest()
        {
        }

        public CheckQuotaForWhiteEstablishmentRequest(int laborOfficeId, long sequenceNumber, int requestedQuota)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
            this.requestedQuota = requestedQuota;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CheckQuotaForWhiteEstablishmentResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class CheckQuotaForWhiteEstablishmentResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public bool CheckQuotaForWhiteEstablishmentResult;

        public CheckQuotaForWhiteEstablishmentResponse()
        {
        }

        public CheckQuotaForWhiteEstablishmentResponse(bool CheckQuotaForWhiteEstablishmentResult)
        {
            this.CheckQuotaForWhiteEstablishmentResult = CheckQuotaForWhiteEstablishmentResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CheckQuotaForWhiteEstablishmentForTargetColor", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class CheckQuotaForWhiteEstablishmentForTargetColor
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int laborOfficeId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public long sequenceNumber;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
        public int requestedQuota;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
        public int targetColorId;

        public CheckQuotaForWhiteEstablishmentForTargetColor()
        {
        }

        public CheckQuotaForWhiteEstablishmentForTargetColor(int laborOfficeId, long sequenceNumber, int requestedQuota, int targetColorId)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
            this.requestedQuota = requestedQuota;
            this.targetColorId = targetColorId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CheckQuotaForWhiteEstablishmentForTargetColorResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class CheckQuotaForWhiteEstablishmentForTargetColor1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public bool CheckQuotaForWhiteEstablishmentForTargetColorResult;

        public CheckQuotaForWhiteEstablishmentForTargetColor1()
        {
        }

        public CheckQuotaForWhiteEstablishmentForTargetColor1(bool CheckQuotaForWhiteEstablishmentForTargetColorResult)
        {
            this.CheckQuotaForWhiteEstablishmentForTargetColorResult = CheckQuotaForWhiteEstablishmentForTargetColorResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEntityCurrentTotalNumberofLaborers", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEntityCurrentTotalNumberofLaborersRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int laborOfficeId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public long sequenceNumber;

        public GetEntityCurrentTotalNumberofLaborersRequest()
        {
        }

        public GetEntityCurrentTotalNumberofLaborersRequest(int laborOfficeId, long sequenceNumber)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEntityCurrentTotalNumberofLaborersResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEntityCurrentTotalNumberofLaborersResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int GetEntityCurrentTotalNumberofLaborersResult;

        public GetEntityCurrentTotalNumberofLaborersResponse()
        {
        }

        public GetEntityCurrentTotalNumberofLaborersResponse(int GetEntityCurrentTotalNumberofLaborersResult)
        {
            this.GetEntityCurrentTotalNumberofLaborersResult = GetEntityCurrentTotalNumberofLaborersResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEntityUnUsedVisas", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEntityUnUsedVisasRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int laborOfficeId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public long sequenceNumber;

        public GetEntityUnUsedVisasRequest()
        {
        }

        public GetEntityUnUsedVisasRequest(int laborOfficeId, long sequenceNumber)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetEntityUnUsedVisasResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetEntityUnUsedVisasResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int GetEntityUnUsedVisasResult;

        public GetEntityUnUsedVisasResponse()
        {
        }

        public GetEntityUnUsedVisasResponse(int GetEntityUnUsedVisasResult)
        {
            this.GetEntityUnUsedVisasResult = GetEntityUnUsedVisasResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ValidateEstablishmentEntityHistory", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class ValidateEstablishmentEntityHistoryRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public int laborOfficeId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public long sequenceNumber;

        public ValidateEstablishmentEntityHistoryRequest()
        {
        }

        public ValidateEstablishmentEntityHistoryRequest(int laborOfficeId, long sequenceNumber)
        {
            this.laborOfficeId = laborOfficeId;
            this.sequenceNumber = sequenceNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ValidateEstablishmentEntityHistoryResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class ValidateEstablishmentEntityHistoryResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public bool ValidateEstablishmentEntityHistoryResult;

        public ValidateEstablishmentEntityHistoryResponse()
        {
        }

        public ValidateEstablishmentEntityHistoryResponse(bool ValidateEstablishmentEntityHistoryResult)
        {
            this.ValidateEstablishmentEntityHistoryResult = ValidateEstablishmentEntityHistoryResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EstablishmentKPIWebServiceSoapChannel : Tamkeen.IndividualsServices.Services.ServiceReference.EstablishmentKPIWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstablishmentKPIWebServiceSoapClient : System.ServiceModel.ClientBase<Tamkeen.IndividualsServices.Services.ServiceReference.EstablishmentKPIWebServiceSoap>, Tamkeen.IndividualsServices.Services.ServiceReference.EstablishmentKPIWebServiceSoap
    {

        public EstablishmentKPIWebServiceSoapClient()
        {
        }

        public EstablishmentKPIWebServiceSoapClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public EstablishmentKPIWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public EstablishmentKPIWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public EstablishmentKPIWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentQuotaResponse GetEstablishmentQuota(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentQuotaRequest request)
        {
            return base.Channel.GetEstablishmentQuota(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentQuotaResponse> GetEstablishmentQuotaAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentQuotaRequest request)
        {
            return base.Channel.GetEstablishmentQuotaAsync(request);
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentColorResponse GetEstablishmentColor(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentColorRequest request)
        {
            return base.Channel.GetEstablishmentColor(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentColorResponse> GetEstablishmentColorAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentColorRequest request)
        {
            return base.Channel.GetEstablishmentColorAsync(request);
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.GetEntitySaudiLaborersCountByEstablishmentNumberResponse GetEntitySaudiLaborersCountByEstablishmentNumber(Tamkeen.IndividualsServices.Services.ServiceReference.GetEntitySaudiLaborersCountByEstablishmentNumberRequest request)
        {
            return base.Channel.GetEntitySaudiLaborersCountByEstablishmentNumber(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEntitySaudiLaborersCountByEstablishmentNumberResponse> GetEntitySaudiLaborersCountByEstablishmentNumberAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEntitySaudiLaborersCountByEstablishmentNumberRequest request)
        {
            return base.Channel.GetEntitySaudiLaborersCountByEstablishmentNumberAsync(request);
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentExcellentLimitResponse GetEstablishmentExcellentLimit(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentExcellentLimitRequest request)
        {
            return base.Channel.GetEstablishmentExcellentLimit(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentExcellentLimitResponse> GetEstablishmentExcellentLimitAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentExcellentLimitRequest request)
        {
            return base.Channel.GetEstablishmentExcellentLimitAsync(request);
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentHighGreenLimitResponse GetEstablishmentHighGreenLimit(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentHighGreenLimitRequest request)
        {
            return base.Channel.GetEstablishmentHighGreenLimit(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentHighGreenLimitResponse> GetEstablishmentHighGreenLimitAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentHighGreenLimitRequest request)
        {
            return base.Channel.GetEstablishmentHighGreenLimitAsync(request);
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.GetEWVAutoApprovalQuotaResponse GetEWVAutoApprovalQuota(Tamkeen.IndividualsServices.Services.ServiceReference.GetEWVAutoApprovalQuotaRequest request)
        {
            return base.Channel.GetEWVAutoApprovalQuota(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEWVAutoApprovalQuotaResponse> GetEWVAutoApprovalQuotaAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEWVAutoApprovalQuotaRequest request)
        {
            return base.Channel.GetEWVAutoApprovalQuotaAsync(request);
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentMediumGreenLimitResponse GetEstablishmentMediumGreenLimit(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentMediumGreenLimitRequest request)
        {
            return base.Channel.GetEstablishmentMediumGreenLimit(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentMediumGreenLimitResponse> GetEstablishmentMediumGreenLimitAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentMediumGreenLimitRequest request)
        {
            return base.Channel.GetEstablishmentMediumGreenLimitAsync(request);
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentLowGreenLimitResponse GetEstablishmentLowGreenLimit(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentLowGreenLimitRequest request)
        {
            return base.Channel.GetEstablishmentLowGreenLimit(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentLowGreenLimitResponse> GetEstablishmentLowGreenLimitAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentLowGreenLimitRequest request)
        {
            return base.Channel.GetEstablishmentLowGreenLimitAsync(request);
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentYellowLimitResponse GetEstablishmentYellowLimit(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentYellowLimitRequest request)
        {
            return base.Channel.GetEstablishmentYellowLimit(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentYellowLimitResponse> GetEstablishmentYellowLimitAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentYellowLimitRequest request)
        {
            return base.Channel.GetEstablishmentYellowLimitAsync(request);
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.GetCompansationVisasForEstablishmentResponse GetCompansationVisasForEstablishment(Tamkeen.IndividualsServices.Services.ServiceReference.GetCompansationVisasForEstablishmentRequest request)
        {
            return base.Channel.GetCompansationVisasForEstablishment(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetCompansationVisasForEstablishmentResponse> GetCompansationVisasForEstablishmentAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetCompansationVisasForEstablishmentRequest request)
        {
            return base.Channel.GetCompansationVisasForEstablishmentAsync(request);
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.GetCompansationVisasForEntityResponse GetCompansationVisasForEntity(Tamkeen.IndividualsServices.Services.ServiceReference.GetCompansationVisasForEntityRequest request)
        {
            return base.Channel.GetCompansationVisasForEntity(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetCompansationVisasForEntityResponse> GetCompansationVisasForEntityAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetCompansationVisasForEntityRequest request)
        {
            return base.Channel.GetCompansationVisasForEntityAsync(request);
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentPendingUnUsedVisasResponse GetEstablishmentPendingUnUsedVisas(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentPendingUnUsedVisasRequest request)
        {
            return base.Channel.GetEstablishmentPendingUnUsedVisas(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentPendingUnUsedVisasResponse> GetEstablishmentPendingUnUsedVisasAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEstablishmentPendingUnUsedVisasRequest request)
        {
            return base.Channel.GetEstablishmentPendingUnUsedVisasAsync(request);
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityPendingUnUsedVisasResponse GetEntityPendingUnUsedVisas(Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityPendingUnUsedVisasRequest request)
        {
            return base.Channel.GetEntityPendingUnUsedVisas(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityPendingUnUsedVisasResponse> GetEntityPendingUnUsedVisasAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityPendingUnUsedVisasRequest request)
        {
            return base.Channel.GetEntityPendingUnUsedVisasAsync(request);
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForVerySmallEntitiesResponse CheckQuotaForVerySmallEntities(Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForVerySmallEntitiesRequest request)
        {
            return base.Channel.CheckQuotaForVerySmallEntities(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForVerySmallEntitiesResponse> CheckQuotaForVerySmallEntitiesAsync(Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForVerySmallEntitiesRequest request)
        {
            return base.Channel.CheckQuotaForVerySmallEntitiesAsync(request);
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForVerySmallEntitiesForTargetColor1 CheckQuotaForVerySmallEntities1(Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForVerySmallEntitiesForTargetColor request)
        {
            return base.Channel.CheckQuotaForVerySmallEntities1(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForVerySmallEntitiesForTargetColor1> CheckQuotaForVerySmallEntities1Async(Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForVerySmallEntitiesForTargetColor request)
        {
            return base.Channel.CheckQuotaForVerySmallEntities1Async(request);
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForWhiteEstablishmentResponse CheckQuotaForWhiteEstablishment(Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForWhiteEstablishmentRequest request)
        {
            return base.Channel.CheckQuotaForWhiteEstablishment(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForWhiteEstablishmentResponse> CheckQuotaForWhiteEstablishmentAsync(Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForWhiteEstablishmentRequest request)
        {
            return base.Channel.CheckQuotaForWhiteEstablishmentAsync(request);
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForWhiteEstablishmentForTargetColor1 CheckQuotaForWhiteEstablishment1(Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForWhiteEstablishmentForTargetColor request)
        {
            return base.Channel.CheckQuotaForWhiteEstablishment1(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForWhiteEstablishmentForTargetColor1> CheckQuotaForWhiteEstablishment1Async(Tamkeen.IndividualsServices.Services.ServiceReference.CheckQuotaForWhiteEstablishmentForTargetColor request)
        {
            return base.Channel.CheckQuotaForWhiteEstablishment1Async(request);
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityCurrentTotalNumberofLaborersResponse GetEntityCurrentTotalNumberofLaborers(Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityCurrentTotalNumberofLaborersRequest request)
        {
            return base.Channel.GetEntityCurrentTotalNumberofLaborers(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityCurrentTotalNumberofLaborersResponse> GetEntityCurrentTotalNumberofLaborersAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityCurrentTotalNumberofLaborersRequest request)
        {
            return base.Channel.GetEntityCurrentTotalNumberofLaborersAsync(request);
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityUnUsedVisasResponse GetEntityUnUsedVisas(Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityUnUsedVisasRequest request)
        {
            return base.Channel.GetEntityUnUsedVisas(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityUnUsedVisasResponse> GetEntityUnUsedVisasAsync(Tamkeen.IndividualsServices.Services.ServiceReference.GetEntityUnUsedVisasRequest request)
        {
            return base.Channel.GetEntityUnUsedVisasAsync(request);
        }

        public Tamkeen.IndividualsServices.Services.ServiceReference.ValidateEstablishmentEntityHistoryResponse ValidateEstablishmentEntityHistory(Tamkeen.IndividualsServices.Services.ServiceReference.ValidateEstablishmentEntityHistoryRequest request)
        {
            return base.Channel.ValidateEstablishmentEntityHistory(request);
        }

        public System.Threading.Tasks.Task<Tamkeen.IndividualsServices.Services.ServiceReference.ValidateEstablishmentEntityHistoryResponse> ValidateEstablishmentEntityHistoryAsync(Tamkeen.IndividualsServices.Services.ServiceReference.ValidateEstablishmentEntityHistoryRequest request)
        {
            return base.Channel.ValidateEstablishmentEntityHistoryAsync(request);
        }
    }
}
